import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from 'components/Footer';

import MainLayout from 'layouts/MainLayout';

const Home: NextPage = () => {
  return (
    <MainLayout>
      <div className="Home">
      <Head>
        <title>Demo Next-js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">main</main>

      <Footer/>
      </div>
    </MainLayout>
  );
};

export default Home;
