import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from 'components/Footer';

import MainLayout from 'layouts/MainLayout';
import LoadedImages from './components/LoadedImages';
import Background from './components/Background';
import Pagination from './components/Pagination';

interface Props {
  data: {
    photos: [];
    total_results: number;
  };
}

const Pexels: NextPage<Props> = ({ data }) => {
  return (
    <MainLayout>
      <div className="Pexels">
        <Head>
          <title>Demo Next-js</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Background />
        <LoadedImages data={data} />
        <Pagination total={data?.total_results} />
      </div>
    </MainLayout>
  );
};

export default Pexels;
